[[redirects]]
  from = "/students.csv"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/staff.csv"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/timetable.csv"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/Subject%20Enrolment%20List.csv"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/UAMQS_Data.xlsx"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "/*.sql"
  to = "/404.html"
  status = 404
  force = true
